Repository dnsmichi/dashing-icinga2, pull requests merged in 2019-10, with the labels that each got.

#73 Add option to show only hard state problems
  README.md
  config/icinga2.json
  lib/icinga2.rb
Labels: enhancement

#74 Add timezone to clock widget
  README.md
  widgets/clock/clock.coffee
  widgets/clock/clock.html
Labels: enhancement

#84 Refactor version parsing and drop the version_revision attribute
  jobs/icinga2.rb
  lib/icinga2.rb
Labels: jobs

#85 Docker: Introduce dnsmichi/dashing-icinga2
  Dockerfile
  README.md
  docker/start.sh
Labels: dashing, enhancement

#88 Support both, Dashing and Smashing as Gems
  Gemfile
  README.md
Labels: dashing, enhancement

#86 Add chartjs widgets to dashboard
  README.md
  assets/javascripts/Chart.bundle.js
  assets/javascripts/Chart.bundle.min.js
  dashboards/icinga2.erb
  dashboards/layout.erb
  jobs/icinga2.rb
  lib/icinga2.rb
  widgets/chartjs/chartjs.coffee
  widgets/chartjs/chartjs.html
Labels: dashboards, enhancement
